openapi: 3.0.3
info:
  title: carrierChoice API
  version: 0.1.0-SNAPSHOT
paths:
  /carrier:
    post:
      summary: Create a new carrier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CarrierCreateRequest"
      responses:
        '201':
          description: Carrier created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CarrierCreateResponse"
  /carrier/compatibilities:
    post:
      summary: Retrieve a list of compatible carriers, ordered by score and price
      requestBody:
        description: Delivery category details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliveryCategoryDto'
      responses:
        '200':
          description: List of compatible carriers, ordered by score and price
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CarrierWithCompatibilityDto'
  /carrier/delivery:
    post:
      summary: Returns the best carrier for a delivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliveryDto'
      responses:
        '200':
          description: Best carrier for the delivery
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarrierDto'
components:
  schemas:
    CarrierCreateRequest:
      type: object
      required:
        - deliveryCategory
        - averageSpeed
        - costPerRide
      properties:
        deliveryCategory:
          $ref: "#/components/schemas/DeliveryCategoryDto"
        averageSpeed:
          $ref: "#/components/schemas/SpeedInMetersPerSecond"
        costPerRide:
          $ref: "#/components/schemas/CostInMillis"
    CarrierCreateResponse:
      type: object
      required:
        - id
        - deliveryCategory
        - averageSpeed
        - costPerRide
      properties:
        id:
          $ref: "#/components/schemas/UUID"
        deliveryCategory:
          $ref: "#/components/schemas/DeliveryCategoryDto"
        averageSpeed:
          $ref: "#/components/schemas/SpeedInMetersPerSecond"
        costPerRide:
          $ref: "#/components/schemas/CostInMillis"
    DeliveryDto:
      type: object
      required:
        - id
        - withdrawal
        - destination
        - deliveryTimeRange
        - packages
      properties:
        id:
          $ref: '#/components/schemas/UUID'
          description: Unique identifier for the delivery.
        withdrawal:
          $ref: '#/components/schemas/PointDto'
          description: The point where the delivery will be picked up.
        destination:
          $ref: '#/components/schemas/PointDto'
          description: The point where the delivery will be dropped off.
        deliveryTimeRange:
          $ref: '#/components/schemas/DeliveryTimeRangeDto'
          description: The time interval during which the delivery will be made.
        packages:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/PackageDto'
          description: The list of packages to be delivered.
    PackageDto:
      type: object
      required:
        - weightInKg
        - volume
      properties:
        weightInKg:
          type: integer
          minimum: 1
          description: The weight of the package in grams.
        volume:
          type: integer
          minimum: 1
          description: The volume of the package in millimeters cubed.
    DeliveryCategoryDto:
      type: object
      required:
        - deliveryTimeRange
        - deliveryArea
        - totalWeight
        - totalVolume
        - maxPackageWeight
      properties:
        deliveryTimeRange:
          $ref: '#/components/schemas/DeliveryTimeRangeDto'
        deliveryArea:
          $ref: '#/components/schemas/AreaDto'
        totalWeight:
          $ref: "#/components/schemas/WeightInGram"
        totalVolume:
          $ref: "#/components/schemas/LongNatural"
        maxPackageWeight:
          $ref: "#/components/schemas/WeightInGram"
    DeliveryTimeRangeDto:
      type: object
      properties:
        startInterval:
          $ref: "#/components/schemas/DateTime"
        endInterval:
          $ref: "#/components/schemas/DateTime"
      required:
        - startInterval
        - endInterval
    AreaDto:
      type: object
      properties:
        center:
          $ref: '#/components/schemas/PointDto'
        radius:
          $ref: "#/components/schemas/IntNatural"
      required:
        - center
        - radius
    PointDto:
      type: object
      properties:
        latitude:
          type: number
          format: double
          minimum: -90
          maximum: 90
        longitude:
          type: number
          format: double
          minimum: -180
          maximum: 180
      required:
        - latitude
        - longitude
    CarrierWithCompatibilityDto:
      type: object
      properties:
        carrier:
          $ref: '#/components/schemas/CarrierDto'
        carrierCompatibility:
          $ref: '#/components/schemas/CarrierCompatibilityDto'
      required:
        - carrier
        - carrierCompatibility
    CarrierDto:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UUID"
        deliveryCategory:
          $ref: '#/components/schemas/DeliveryCategoryDto'
        averageSpeed:
          $ref: "#/components/schemas/SpeedInMetersPerSecond"
        costPerRide:
          $ref: "#/components/schemas/CostInMillis"
      required:
        - id
        - deliveryCategory
        - averageSpeed
        - costPerRide
    CarrierCompatibilityDto:
      type: string
      enum:
        - FULLY_COMPATIBLE
        - PARTIALLY_COMPATIBLE
        - NOT_COMPATIBLE
    UUID:
      type: string
      format: uuid
    DateTime:
      type: string
      format: date-time
    WeightInGram:
      $ref: "#/components/schemas/LongNatural"
    SpeedInMetersPerSecond:
      $ref: "#/components/schemas/NonZeroIntNatural"
    CostInMillis:
      $ref: "#/components/schemas/LongNatural"
    LongNatural:
      type: integer
      format: int64
      minimum: 0
    IntNatural:
      type: integer
      format: int32
      minimum: 0
    NonZeroIntNatural:
      type: integer
      format: int32
      minimum: 1